### ISSUE TITLE
Add +5v regulator onboard

### ISSUE THREAD

**Issue by aurimasniekis** [TechAUmNu/A200S#1]
Hi, I just noticed that +5V rail regulator is missing in schematic

**Comment by TechAUmNu** [comment]
This is powered by 5v from an external source such as a BEC. So there is no regulator.

**Comment by TechAUmNu** [comment]
I will be adding a 5v regulator for the next version.

**Comment by aurimasniekis** [comment]
It's OK I was reviewing your schematic and was like where is +5V rail 😄

How is 100V LDO handling its job? Some close engineer friends made fun of me when I told that I want to use LDO for 80V to 12V

**Comment by TechAUmNu** [comment]
I mean its not exactly efficient for power but when its already dissipating 80W who cares about another 1 or 2 watts! 😃 Plus it saves cost, board space and reduces the component count a bunch.

**Comment by TechAUmNu** [comment]
V1.3 has DC-DC for 9-30v input.
